modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU General Public License v3.0"

[[mods]]
modId = "tracksta"
version = "${version}"
displayName = "Create Station Essentials"
authors = "ProgrammerLP"
description = '''
Mod that adds building blocks for tracks and stations. e.g. Platform Sign Blocks and Noise Isolation Walls.
'''
logoFile = "mod_icon.png"

[[dependencies.tracksta]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tracksta]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tracksta]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.tracksta]]
modId = "dragonlib"
type = "required"
versionRange = "[beta-3.0.23,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tracksta]]
modId = "create"
type = "required"
versionRange = "[6.0.7,]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "tracksta.mixins.json"

